up:
	docker compose -f frepple.compose.yaml up -d

down:
	docker compose -f frepple.compose.yaml down

reset:
	docker compose -f frepple.compose.yaml down -v

logs:
	docker compose -f frepple.compose.yaml logs -f

pull:
	docker compose -f frepple.compose.yaml pull
